name: Build images on push to master

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-executor:
    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF: ${{ github.ref }}
      PLATFORMS: "linux/amd64,linux/arm64,linux/s390x"

    runs-on: ubuntu-latest
    steps:
    - name: Clone source code
      uses: actions/checkout@v2

    - name: Get the tags
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ env.PLATFORMS }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: kunlu20
        password: 4f850c08-489a-4b71-9deb-eb75138258ad

    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./deploy/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/s390x
        push: true
        tags: |
          docker.io/kunlu20/executor:${{ env.GITHUB_SHA }}
          docker.io/kunlu20/executor:${{ steps.vars.outputs.tag }}
          docker.io/kunlu20/executor:latest
    
    - name: Sign images 
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v0.2.0'

  build-debug:
    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF: ${{ github.ref }}
      PLATFORMS: "linux/amd64,linux/arm64"
    runs-on: ubuntu-latest
    steps:
    - name: Clone source code
      uses: actions/checkout@v2

    - name: Get the tags
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ env.PLATFORMS }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: kunlu20
        password: 4f850c08-489a-4b71-9deb-eb75138258ad

    - uses: docker/build-push-action@v2
      with:
        context: .
        file:  ./deploy/Dockerfile_debug
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          docker.io/kunlu20/executor:${{ env.GITHUB_SHA }}-debug
          docker.io/kunlu20/executor:${{ steps.vars.outputs.tag }}-debug
          docker.io/kunlu20/executor:debug

    - name: Sign images 
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v0.2.0'

  build-warmer:
    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF: ${{ github.ref }}
      PLATFORMS: "linux/amd64,linux/arm64,linux/s390x"
    runs-on: ubuntu-latest
    steps:
    - name: Clone source code
      uses: actions/checkout@v2

    - name: Get the tags
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ env.PLATFORMS }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: kunlu20
        password: 4f850c08-489a-4b71-9deb-eb75138258ad

    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./deploy/Dockerfile_warmer
        platforms: linux/amd64,linux/arm64,linux/s390x
        push: true
        tags: |
          docker.io/kunlu20/warmer:${{ env.GITHUB_SHA }}
          docker.io/kunlu20/warmer:${{ steps.vars.outputs.tag }}
          docker.io/kunlu20/warmer:latest

    - name: Sign images 
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v0.2.0'


  build-slim:
    env:
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF: ${{ github.ref }}
      PLATFORMS: "linux/amd64,linux/arm64,linux/s390x,linux/ppc64le"

    runs-on: ubuntu-latest
    steps:
    - name: Clone source code
      uses: actions/checkout@v2

    - name: Get the tags
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ env.PLATFORMS }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: kunlu20
        password: 4f850c08-489a-4b71-9deb-eb75138258ad

    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./deploy/Dockerfile_slim
        platforms: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
        push: true
        tags: |
          docker.io/kunlu20/executor:${{ env.GITHUB_SHA }}-slim
          docker.io/kunlu20/executor:${{ steps.vars.outputs.tag }}-slim
          docker.io/kunlu20/executor:slim
